"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['start.py']
# 自写模块放在DATA_FILES列表中
DATA_FILES = ['BasicAlgebra.py', 'Lexer.py', 'Matrix.py', 'Parser.py', 'Statistics.py', 'Vector.py']
# 第三方库放在OPTIONS下的includes对应的列表中
OPTIONS = {'includes': ['scipy', 'typing', 'math', 'enum']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
